
/* 
*********************************** Make the environment ***********************************

sudo apt-get update
sudo apt-get install mysql-server

sudo mysql_secure_installation -- Secure Install 

sudo ufw allow mysql -- Allow remote access 
systemctl start mysql -- Start the MySQL service 
systemctl enable mysql -- Launch at reboot 

/usr/bin/mysql -u root -p -- Start the mysql shell with the password entered in mysql_secure_installation 

*/



UPDATE mysql.user SET authentication_string = PASSWORD('password') WHERE User = 'root'; /* set password for root user */
FLUSH PRIVILEGES;


SELECT User, Host, authentication_string FROM mysql.user; /* View Users */



CREATE DATABASE demodb; /* Create Database */

SHOW DATABASES;


INSERT INTO mysql.user (User,Host,authentication_string,ssl_cipher,x509_issuer,x509_subject)
VALUES('demouser','localhost',PASSWORD('demopassword'),'','',''); /* Add User */

FLUSH PRIVILEGES;

GRANT ALL PRIVILEGES ON demodb.* to demouser@localhost; /* Grant database user permissions */

SHOW GRANTS FOR 'demouser'@'localhost';


/* Our instructions save in the following table */
CREATE TABLE ResultsDB.InstructionsTable (
    InstrID INT NOT NULL AUTO_INCREMENT,
    Mnemonic VARCHAR(20) DEFAULT NULL, 
    Operand1 VARCHAR(100) DEFAULT NULL, 
    Operand2 VARCHAR(100) DEFAULT NULL, 
    Operand3 VARCHAR(100) DEFAULT NULL, 
    HexCode VARCHAR(100) DEFAULT NULL, 
  	PRIMARY KEY (InstrID)
);

/* This table saves the bare results of nanoBench */
CREATE TABLE ResultsDB.NanoBenchResults (
  NanoID INT NOT NULL AUTO_INCREMENT,
  Instruction TEXT DEFAULT NULL,
  InstrID INT ,
  BR_INST_RETIRED_ALL_BRANCHES VARCHAR(20) DEFAULT NULL,
  BR_MISP_RETIRED_LL_BRANCHES VARCHAR(20) DEFAULT NULL,
  Corecycles VARCHAR(20) DEFAULT NULL,
  Instructionsretired VARCHAR(20) DEFAULT NULL,
  MEM_LOAD_RETIRED_L1_HIT VARCHAR(20) DEFAULT NULL,
  MEM_LOAD_RETIRED_L1_MISS VARCHAR(20) DEFAULT NULL,
  MEM_LOAD_RETIRED_L2_HIT VARCHAR(20) DEFAULT NULL,
  MEM_LOAD_RETIRED_L2_MISS VARCHAR(20) DEFAULT NULL, 
  MEM_LOAD_RETIRED_L3_HIT VARCHAR(20) DEFAULT NULL,
  MEM_LOAD_RETIRED_L3_MISS VARCHAR(20) DEFAULT NULL,
  RDTSC VARCHAR(20) DEFAULT NULL, 
  Referencecycles VARCHAR(20) DEFAULT NULL,
  UOPS_DISPATCHED_PORT_PORT_0 VARCHAR(20) DEFAULT NULL,
  UOPS_DISPATCHED_PORT_PORT_1 VARCHAR(20) DEFAULT NULL, 
  UOPS_DISPATCHED_PORT_PORT_2 VARCHAR(20) DEFAULT NULL,
  UOPS_DISPATCHED_PORT_PORT_3 VARCHAR(20) DEFAULT NULL,
  UOPS_DISPATCHED_PORT_PORT_4 VARCHAR(20) DEFAULT NULL, 
  UOPS_DISPATCHED_PORT_PORT_5 VARCHAR(20) DEFAULT NULL,
  UOPS_DISPATCHED_PORT_PORT_6 VARCHAR(20) DEFAULT NULL,
  UOPS_DISPATCHED_PORT_PORT_7 VARCHAR(20) DEFAULT NULL,  
  UOPS_EXECUTED_THREAD VARCHAR(20) DEFAULT NULL,
  UOPS_ISSUED_ANY VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (NanoID)
);
 /* This table saves the results of likwid */

CREATE TABLE ResultsDB.PerformanceCounterResults (
    likwidID INT NOT NULL AUTO_INCREMENT,
    ARITH_DIVIDER_ACTIVE VARCHAR(20) DEFAULT NULL,
    ARITH_DIVIDER_COUNT VARCHAR(20) DEFAULT NULL ,
    AVX_DP_MFLOP_per_s VARCHAR(20) DEFAULT NULL ,
    AVX_SP_MFLOP_per_s VARCHAR(20) DEFAULT NULL ,
    Avg_stall_duration_cycles VARCHAR(20) DEFAULT NULL ,
    Avg_divide_unit_usage_duration VARCHAR(20) DEFAULT NULL ,
    Avg_recovery_duration VARCHAR(20) DEFAULT NULL ,
    BR_INST_RETIRED_ALL_BRANCHES VARCHAR(20) DEFAULT NULL ,
    BR_MISP_RETIRED_ALL_BRANCHES VARCHAR(20) DEFAULT NULL ,
    Back_End_percent VARCHAR(20) DEFAULT NULL ,
    Branch_misprediction_rate VARCHAR(20) DEFAULT NULL ,
    Branch_misprediction_ratio VARCHAR(20) DEFAULT NULL ,
    Branch_rate VARCHAR(20) DEFAULT NULL ,
    CPI VARCHAR(20) DEFAULT NULL ,
    CPU_CLK_UNHALTED_CORE VARCHAR(20) DEFAULT NULL ,
    CPU_CLK_UNHALTED_REF VARCHAR(20) DEFAULT NULL ,
    CPU_CLOCK_UNHALTED_TOTAL_CYCLES VARCHAR(20) DEFAULT NULL ,
    CYCLE_ACTIVITY_CYCLES_L1D_PENDING VARCHAR(20) DEFAULT NULL ,
    CYCLE_ACTIVITY_CYCLES_L2_PENDING VARCHAR(20) DEFAULT NULL ,
    CYCLE_ACTIVITY_CYCLES_LDM_PENDING VARCHAR(20) DEFAULT NULL ,
    CYCLE_ACTIVITY_CYCLES_NO_EXECUTE VARCHAR(20) DEFAULT NULL ,
    CYCLE_ACTIVITY_STALLS_L1D_PENDING VARCHAR(20) DEFAULT NULL ,
    CYCLE_ACTIVITY_STALLS_L2_PENDING VARCHAR(20) DEFAULT NULL ,
    CYCLE_ACTIVITY_STALLS_LDM_PENDING VARCHAR(20) DEFAULT NULL ,
    CYCLE_ACTIVITY_STALLS_TOTAL VARCHAR(20) DEFAULT NULL ,
    Clock_MHz VARCHAR(20) DEFAULT NULL ,
    Cycles_without_execution_percent VARCHAR(20) DEFAULT NULL ,
    Cycles_without_execution_due_to_L1D_percent VARCHAR(20) DEFAULT NULL,
    Cycles_without_execution_due_to_L2_percent VARCHAR(20) DEFAULT NULL,
    Cycles_without_execution_due_to_memory_loads_percent VARCHAR(20) DEFAULT NULL ,
    DP_MFLOP_per_s VARCHAR(20) DEFAULT NULL ,
    DTLB_LOAD_MISSES_CAUSES_A_WALK VARCHAR(20) DEFAULT NULL ,
    DTLB_LOAD_MISSES_WALK_ACTIVE VARCHAR(20) DEFAULT NULL ,
    DTLB_STORE_MISSES_CAUSES_A_WALK VARCHAR(20) DEFAULT NULL ,
    DTLB_STORE_MISSES_WALK_ACTIVE VARCHAR(20) DEFAULT NULL ,
    Energy_DRAM_J VARCHAR(20) DEFAULT NULL ,
    Energy_PP0_J VARCHAR(20) DEFAULT NULL ,
    Energy_PP1_J VARCHAR(20) DEFAULT NULL ,
    Energy_J VARCHAR(20) DEFAULT NULL ,
    Executed_UOPs VARCHAR(20) DEFAULT NULL ,
    Execution_stall_rate_percent VARCHAR(20) DEFAULT NULL ,
    FP_ARITH_INST_RETIRED_128B_PACKED_DOUBLE VARCHAR(20) DEFAULT NULL ,
    FP_ARITH_INST_RETIRED_128B_PACKED_SINGLE VARCHAR(20) DEFAULT NULL ,
    FP_ARITH_INST_RETIRED_256B_PACKED_DOUBLE VARCHAR(20) DEFAULT NULL ,
    FP_ARITH_INST_RETIRED_256B_PACKED_SINGLE VARCHAR(20) DEFAULT NULL ,
    FP_ARITH_INST_RETIRED_SCALAR_DOUBLE VARCHAR(20) DEFAULT NULL ,
    FP_ARITH_INST_RETIRED_SCALAR_SINGLE VARCHAR(20) DEFAULT NULL ,
    Fetch_Bubbles VARCHAR(20) DEFAULT NULL ,
    FirstOperand VARCHAR(100) DEFAULT NULL ,
    Front_End_percent VARCHAR(20) DEFAULT NULL ,
    ICACHE_64B_IFTAG_ALL VARCHAR(20) DEFAULT NULL ,
    ICACHE_64B_IFTAG_MISS VARCHAR(20) DEFAULT NULL ,
    ICACHE_64B_IFTAG_STALL VARCHAR(20) DEFAULT NULL ,
    IDQ_UOPS_NOT_DELIVERED_CORE VARCHAR(20) DEFAULT NULL ,
    INSTR_RETIRED_ANY VARCHAR(20) DEFAULT NULL ,
    INT_MISC_RECOVERY_COUNT VARCHAR(20) DEFAULT NULL ,
    INT_MISC_RECOVERY_CYCLES VARCHAR(20) DEFAULT NULL ,
    IPC VARCHAR(20) DEFAULT NULL ,
    ITLB_MISSES_CAUSES_A_WALK VARCHAR(20) DEFAULT NULL ,
    ITLB_MISSES_WALK_ACTIVE VARCHAR(20) DEFAULT NULL ,
    InstructionID VARCHAR(20) DEFAULT NULL ,
    Instructions_per_branch VARCHAR(20) DEFAULT NULL ,
    Issued_UOPs VARCHAR(20) DEFAULT NULL ,
    L1_DTLB_load_miss_duration_Cyc VARCHAR(20) DEFAULT NULL ,
    L1_DTLB_load_miss_rate VARCHAR(20) DEFAULT NULL ,
    L1_DTLB_load_misses VARCHAR(20) DEFAULT NULL ,
    L1_DTLB_store_miss_duration_Cyc VARCHAR(20) DEFAULT NULL ,
    L1_DTLB_store_miss_rate VARCHAR(20) DEFAULT NULL ,
    L1_DTLB_store_misses VARCHAR(20) DEFAULT NULL ,
    L1_ITLB_miss_duration_Cyc VARCHAR(20) DEFAULT NULL ,
    L1_ITLB_miss_rate VARCHAR(20) DEFAULT NULL ,
    L1_ITLB_misses VARCHAR(20) DEFAULT NULL ,
    L1D_M_EVICT VARCHAR(20) DEFAULT NULL ,
    L1D_REPLACEMENT VARCHAR(20) DEFAULT NULL ,
    L1I_miss_rate VARCHAR(20) DEFAULT NULL ,
    L1I_miss_ratio VARCHAR(20) DEFAULT NULL ,
    L1I_request_rate VARCHAR(20) DEFAULT NULL ,
    L1I_stall_rate VARCHAR(20) DEFAULT NULL ,
    L1I_stalls VARCHAR(20) DEFAULT NULL ,
    L2_bandwidth_MBytes_per_s VARCHAR(20) DEFAULT NULL ,
    L2_data_volume_GBytes VARCHAR(20) DEFAULT NULL ,
    L2_miss_rate VARCHAR(20) DEFAULT NULL ,
    L2_miss_ratio VARCHAR(20) DEFAULT NULL ,
    L2_request_rate VARCHAR(20) DEFAULT NULL,
    L2D_evict_bandwidth_MBytes_per_s VARCHAR(20) DEFAULT NULL ,
    L2D_evict_data_volume_GBytes VARCHAR(20) DEFAULT NULL ,
    L2D_load_bandwidth_MBytes_per_s VARCHAR(20) DEFAULT NULL,
    L2D_load_data_volume_GBytes VARCHAR(20) DEFAULT NULL ,
    L2_LINES_IN_ALL VARCHAR(20) DEFAULT NULL ,
    L2_RQSTS_MISS VARCHAR(20) DEFAULT NULL ,
    L2_TRANS_ALL_REQUESTS VARCHAR(20) DEFAULT NULL ,
    L2_TRANS_L2_WB VARCHAR(20) DEFAULT NULL ,
    L3_bandwidth_MBytes_per_s VARCHAR(20) DEFAULT NULL ,
    L3_data_volume_GBytes VARCHAR(20) DEFAULT NULL ,
    L3_evict_bandwidth_MBytes_per_s VARCHAR(20) DEFAULT NULL ,
    L3_evict_data_volume_GBytes VARCHAR(20) DEFAULT NULL ,
    L3_load_bandwidth_MBytes_per_s VARCHAR(20) DEFAULT NULL ,
    L3_load_data_volume_GBytes VARCHAR(20) DEFAULT NULL ,
    L3_miss_rate VARCHAR(20) DEFAULT NULL ,
    L3_miss_ratio VARCHAR(20) DEFAULT NULL ,
    L3_request_rate VARCHAR(20) DEFAULT NULL ,
    Load_to_store_ratio VARCHAR(20) DEFAULT NULL ,
    Local_LLC_false_sharing_MByte VARCHAR(20) DEFAULT NULL ,
    Local_LLC_false_sharing_rate VARCHAR(20) DEFAULT NULL ,
    MEM_INST_RETIRED_ALL VARCHAR(20) DEFAULT NULL ,
    MEM_INST_RETIRED_ALL_LOADS VARCHAR(20) DEFAULT NULL ,
    MEM_INST_RETIRED_ALL_STORES VARCHAR(20) DEFAULT NULL ,
    MEM_LOAD_L3_HIT_RETIRED_XSNP_HITM VARCHAR(20) DEFAULT NULL,
    MEM_LOAD_RETIRED_L3_HIT VARCHAR(20) DEFAULT NULL ,
    MEM_LOAD_RETIRED_L3_MISS VARCHAR(20) DEFAULT NULL ,
    Memory_bandwidth_MBytes_per_s VARCHAR(20) DEFAULT NULL,
    Memory_data_volume_GBytes VARCHAR(20) DEFAULT NULL ,
    Memory_evict_bandwidth_MBytes_per_s VARCHAR(20) DEFAULT NULL,
    Memory_evict_data_volume_GBytes VARCHAR(20) DEFAULT NULL ,
    Memory_load_bandwidth_MBytes_per_s VARCHAR(20) DEFAULT NULL,
    Memory_load_data_volume_GBytes VARCHAR(20) DEFAULT NULL,
    Mnemonic VARCHAR(40) DEFAULT NULL ,
    Number_of_divide_ops VARCHAR(20) DEFAULT NULL ,
    Operational_intensity VARCHAR(20) DEFAULT NULL,
    PWR_DRAM_ENERGY VARCHAR(20) DEFAULT NULL ,
    PWR_PKG_ENERGY VARCHAR(20) DEFAULT NULL ,
    PWR_PP0_ENERGY VARCHAR(20) DEFAULT NULL ,
    PWR_PP1_ENERGY VARCHAR(20) DEFAULT NULL ,
    Packed_DP_MFLOP_per_s VARCHAR(20) DEFAULT NULL ,
    Packed_MUOPS_per_s VARCHAR(20) DEFAULT NULL ,
    Packed_SP_MFLOP_per_s VARCHAR(20) DEFAULT NULL ,
    Port0_usage_ratio VARCHAR(20) DEFAULT NULL ,
    Port1_usage_ratio VARCHAR(20) DEFAULT NULL ,
    Port2_usage_ratio VARCHAR(20) DEFAULT NULL ,
    Port3_usage_ratio VARCHAR(20) DEFAULT NULL ,
    Port4_usage_ratio VARCHAR(20) DEFAULT NULL ,
    Port5_usage_ratio VARCHAR(20) DEFAULT NULL ,
    Port6_usage_ratio VARCHAR(20) DEFAULT NULL ,
    Port7_usage_ratio VARCHAR(20) DEFAULT NULL ,
    Power_DRAM_W VARCHAR(20) DEFAULT NULL,
    Power_PP0_W VARCHAR(20) DEFAULT NULL ,
    Power_PP1_W VARCHAR(20) DEFAULT NULL ,
    Power_W VARCHAR(20) DEFAULT NULL ,
    Recovery_Bubbles VARCHAR(20) DEFAULT NULL ,
    Retired_UOPs VARCHAR(20) DEFAULT NULL ,
    Retiring_percent VARCHAR(20) DEFAULT NULL ,
    Runtime_RDTSC_s VARCHAR(20) DEFAULT NULL ,
    Runtime_unhalted_s VARCHAR(20) DEFAULT NULL ,
    SP_MFLOP_per_s VARCHAR(20) DEFAULT NULL ,
    Scalar_MUOPS_per_s VARCHAR(20) DEFAULT NULL,
    SecondOperand VARCHAR(100) DEFAULT NULL  ,
    Slots_Retired VARCHAR(20) DEFAULT NULL ,
    Speculation_percent VARCHAR(20) DEFAULT NULL ,
    Stalls_caused_by_L1D_misses_percent VARCHAR(20) DEFAULT NULL ,
    Stalls_caused_by_L1D_misses_rate_percent VARCHAR(20) DEFAULT NULL ,
    Stalls_caused_by_L2_misses_percent VARCHAR(20) DEFAULT NULL ,
    Stalls_caused_by_L2_misses_rate_percent VARCHAR(20) DEFAULT NULL ,
    Stalls_caused_by_memory_loads_percent VARCHAR(20) DEFAULT NULL ,
    Stalls_caused_by_memory_loads_rate_percent VARCHAR(20) DEFAULT NULL ,
    TEMP_CORE VARCHAR(20) DEFAULT NULL ,
    Temperature_C VARCHAR(20) DEFAULT NULL ,
    ThirdOperand VARCHAR(100) DEFAULT NULL  ,
    Total_Slots VARCHAR(20) DEFAULT NULL ,
    Total_execution_stalls VARCHAR(20) DEFAULT NULL ,
    UNCORE_CLOCK VARCHAR(20) DEFAULT NULL ,
    UOPS_DISPATCHED_PORT_PORT_0 VARCHAR(20) DEFAULT NULL ,
    UOPS_DISPATCHED_PORT_PORT_1 VARCHAR(20) DEFAULT NULL ,
    UOPS_DISPATCHED_PORT_PORT_2 VARCHAR(20) DEFAULT NULL ,
    UOPS_DISPATCHED_PORT_PORT_3 VARCHAR(20) DEFAULT NULL,
    UOPS_EXECUTED_STALL_CYCLES VARCHAR(20) DEFAULT NULL ,
    UOPS_EXECUTED_THREAD VARCHAR(20) DEFAULT NULL ,
    UOPS_EXECUTED_USED_CYCLES VARCHAR(20) DEFAULT NULL,
    UOPS_ISSUED_ANY VARCHAR(20) DEFAULT NULL ,
    UOPS_ISSUED_STALL_CYCLES VARCHAR(20) DEFAULT NULL ,
    UOPS_ISSUED_USED_CYCLES VARCHAR(20) DEFAULT NULL ,
    UOPS_RETIRED_ALL VARCHAR(20) DEFAULT NULL ,
    UOPS_RETIRED_RETIRE_SLOTS VARCHAR(20) DEFAULT NULL,
    UOPS_RETIRED_STALL_CYCLES VARCHAR(20) DEFAULT NULL,
    UOPS_RETIRED_USED_CYCLES VARCHAR(20) DEFAULT NULL,
    Uncore_Clock_MHz VARCHAR(20) DEFAULT NULL,
    Unused_cycles_ratio_percent VARCHAR(20) DEFAULT NULL,
    Used_cycles_ratio_percent VARCHAR(20) DEFAULT NULL,
    Vectorization_ratio VARCHAR(20) DEFAULT NULL,
    instruction VARCHAR(50) DEFAULT NULL ,
  	PRIMARY KEY (likwidID)
);

